// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbbHbSefqK8QjAK6HtupTdHKsH2-HeN6I',
    appId: '1:697610004897:web:f66da5ca40d47658e903e0',
    messagingSenderId: '697610004897',
    projectId: 'quran-d45b1',
    authDomain: 'quran-d45b1.firebaseapp.com',
    storageBucket: 'quran-d45b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdlE6iYPoiO8NxfBuLjxrickdtU_emPyA',
    appId: '1:697610004897:android:10cd724286ebe2fbe903e0',
    messagingSenderId: '697610004897',
    projectId: 'quran-d45b1',
    storageBucket: 'quran-d45b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFC4O1dtl1oAPwvIkZd_xqswJNkyAJAnQ',
    appId: '1:697610004897:ios:fa4c690b1ea94ca6e903e0',
    messagingSenderId: '697610004897',
    projectId: 'quran-d45b1',
    storageBucket: 'quran-d45b1.firebasestorage.app',
    iosBundleId: 'com.example.quranapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFC4O1dtl1oAPwvIkZd_xqswJNkyAJAnQ',
    appId: '1:697610004897:ios:fa4c690b1ea94ca6e903e0',
    messagingSenderId: '697610004897',
    projectId: 'quran-d45b1',
    storageBucket: 'quran-d45b1.firebasestorage.app',
    iosBundleId: 'com.example.quranapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbbHbSefqK8QjAK6HtupTdHKsH2-HeN6I',
    appId: '1:697610004897:web:f173e0299f0c7effe903e0',
    messagingSenderId: '697610004897',
    projectId: 'quran-d45b1',
    authDomain: 'quran-d45b1.firebaseapp.com',
    storageBucket: 'quran-d45b1.firebasestorage.app',
  );

}